server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name mmovasseghi.duckdns.org 155.117.13.123 _;

    root /var/www/mmovasseghi/out;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
